#!/bin/sh

. libtest.sh
. libgit.sh

export GIT_EDITOR=\$EDITOR

tigrc <<EOF
set side-by-side = yes
set line-graphics = ascii
EOF

git_init

in_work_dir git_add a.txt "$(printf 'one\ntwo\nthree')"
in_work_dir git_commit -m "Initial commit"
in_work_dir file a.txt <<EOF
one
two
three
four
EOF
in_work_dir git add a.txt
in_work_dir git_commit -m "Add a line and a trailing newline"

steps '
	:/[-]three$
	:save-view search.view
	:exec !vim +%(lineno) %(file)
	:/[+]four
	:exec !vim +%(lineno) %(file)
	:save-display no-newline.screen
'

test_tig show HEAD

sed -n "s/^Position: /search: /p" search.view > positions

assert_equals 'no-newline.screen' <<EOF
commit cd20b61d3dcc66864c6ee2f48f667484402f4bb2
Refs: [master]
Author:     Committer <c.ommitter@example.net>
AuthorDate: Fri Feb 13 23:31:30 2009 +0000
Commit:     Committer <c.ommitter@example.net>
CommitDate: Fri Feb 13 23:31:30 2009 +0000

    Add a line and a trailing newline
---
 a.txt | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

--------------------------------------------------------------------------------
diff --git a/a.txt b/a.txt
index 54d55bf..f384549 100644
--- a/a.txt
+++ b/a.txt
--------------------------------------------------------------------------------
@@ -1,3 +1,4 @@
---------------------------------------+----------------------------------------
 one                                   | one
 two                                   | two
-three                                 |+three
                                       |+four
\ No newline at end of file            |



[diff] Changes to 'a.txt' - line 24 of 25                                   100%
EOF

assert_equals 'editor.log' <<EOF
+3 a.txt
three
+4 a.txt
four
EOF

assert_equals 'positions' <<EOF
search: offset=0 column=0 lineno=22
EOF
